### PR TITLE
Fix #36, and set-up the Feed tab.

### LINKED ISSUE #36: Add button crash
Sometimes selecting the "Add" button under follows results in this crash:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.cmput301.cmput301w127t06.moodbook, PID: 3052
                  java.util.ConcurrentModificationException
                      at java.util.ArrayList$Itr.next(ArrayList.java:831)
                      at com.cmput301.cmput301w127t06.moodbook.Follows.removeFromFollowRequests(Follows.java:212)
                      at com.cmput301.cmput301w127t06.moodbook.FollowListAdapter$2.onClick(FollowListAdapter.java:202)
                      at android.view.View.performClick(View.java:5637)
                      at android.view.View$PerformClick.run(View.java:22429)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### PR DESCRIPTION
**Pull request by ZackerySpytz**
Mood events from users we are following will be shown in the Feed tab.

### CODE REVIEW

File: app/src/main/java/com/cmput301/cmput301w127t06/moodbook/Follows.java [hunk 1]
```diff
@@ -192,33 +193,44 @@ public void addToFollowingRequests(String username, String userID){
...
+     *
+     * In order to properly remove items from lists while iterating in Java (in these next few
+     * methods):
+     * http://stackoverflow.com/a/13533741 found Mar 31 '17.
      */
     public void removeFromFollowing(String username){
-        for (User user : followingList){
-            if (user.getUsername()== username)
-                followingList.remove(user);
+        for(Iterator<User> it = followingList.iterator(); it.hasNext();) {
```
Comment (Everlag) [inline app/src/main/java/com/cmput301/cmput301w127t06/moodbook/Follows.java]: Delicious iterators

Comment (ZackerySpytz) [inline app/src/main/java/com/cmput301/cmput301w127t06/moodbook/Follows.java]: I know!
